export const routes = {
  home: "/",
  wiki: "/wiki",
  wikiMusic: "/wiki/music",
  wikiSong: (songId: string) => `/wiki/music/songs/${encodeURIComponent(songId)}`,
  wikiStory: "/wiki/story",
  wikiWorld: "/wiki/world",
  wikiCourse: "/wiki/course",
  wikiAchievements: "/wiki/achievements",
  wikiNetwork: "/wiki/network",
  wikiElement: (slug = "gameplay") => `/wiki/elements/${encodeURIComponent(slug)}`,
  tools: "/tools",
  about: "/about",
  announcements: "/about/announcements",
  status: "/about/status",
  support: "/about/support",
} as const;
